//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW3_20152C_Maraton
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PW3_20152C_TP2_MaratonesEntities : DbContext
    {
        public PW3_20152C_TP2_MaratonesEntities()
            : base("name=PW3_20152C_TP2_MaratonesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Maraton> Maraton { get; set; }
        public DbSet<ResultadoMaratonParticipante> ResultadoMaratonParticipante { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
