//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW3_20152C_Maraton
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoMaratonParticipante
    {
        public int IdUsuario { get; set; }
        public int IdMaraton { get; set; }
        public int NroInscripcion { get; set; }
        public Nullable<int> PosicionFinal { get; set; }
        public Nullable<int> TiempoLlegada { get; set; }
        public Nullable<bool> Finalizo { get; set; }
    
        public virtual Maraton Maraton { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
